### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by mymedia2** [mymedia2/technosphere#1]
- [x] разобраться с имеющимся pretty-print и написать свой
- [ ] вывести самую простую диагностику
- [ ] посмотреть, как устроены тесты
- [ ] добавить документацию в invoke.texi
